/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.io.IOException;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class Interfaccia extends javax.swing.JFrame {

    /**
     * Creates new form Interfaccia
     */
    String temp;
    public Interfaccia() {
        String ris=JOptionPane.showInputDialog(null, "qual'è il tuo nome?","Information",JOptionPane.OK_CANCEL_OPTION);
        initComponents();
        Condivisi.Instance().setI(this);
        Condivisi.Instance().mioNome=ris;
        temp="";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButConnetti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtMessaggi = new javax.swing.JTextArea();
        TxtIp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Disconnetti = new javax.swing.JButton();
        butInviaMess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txtmessaggio = new javax.swing.JTextArea();
        TxtStatiConnessione = new javax.swing.JLabel();
        Annulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButConnetti.setText("Connetti");
        ButConnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConnettiActionPerformed(evt);
            }
        });

        TxtMessaggi.setColumns(20);
        TxtMessaggi.setRows(5);
        jScrollPane1.setViewportView(TxtMessaggi);

        jLabel1.setText("Ip destinatario:");

        Disconnetti.setText("disconnetti");
        Disconnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnettiActionPerformed(evt);
            }
        });

        butInviaMess.setText("invia messaggio");
        butInviaMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInviaMessActionPerformed(evt);
            }
        });

        jLabel2.setText("Messaggio");

        Txtmessaggio.setColumns(20);
        Txtmessaggio.setRows(5);
        jScrollPane2.setViewportView(Txtmessaggio);

        Annulla.setText("annulla");
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butInviaMess))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ButConnetti))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addComponent(Disconnetti))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(TxtStatiConnessione, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(Annulla))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButConnetti)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butInviaMess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Disconnetti)
                .addGap(15, 15, 15)
                .addComponent(TxtStatiConnessione, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Annulla)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butInviaMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInviaMessActionPerformed
        if(Condivisi.Instance().getConnessioneAttule()!=null)
        {
            Pacchetto p=new Pacchetto("m",Txtmessaggio.getText());
            p.address=Condivisi.Instance().getConnessioneAttule();
            Condivisi.Instance().MettiPacchettoOut(p);
            TxtIp.setText("");
        }
    }//GEN-LAST:event_butInviaMessActionPerformed

    private void DisconnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnettiActionPerformed
        if(Condivisi.Instance().getConnessioneAttule()!=null)
        {
            Pacchetto p=new Pacchetto("d","");
            p.address=Condivisi.Instance().getConnessioneAttule();
            Condivisi.Instance().MettiPacchettoOut(p);
            Condivisi.Instance().SettaStatoConnessione(StatoConnessione.DisConnesso);
        }
    }//GEN-LAST:event_DisconnettiActionPerformed

    private void ButConnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConnettiActionPerformed
        Pacchetto p=new Pacchetto("c",Condivisi.Instance().mioNome);
        try {
            p.address=InetAddress.getByName(TxtIp.getText());
            Condivisi.Instance().MettiPacchettoOut(p);
            Condivisi.Instance().SettaStatoConnessione(StatoConnessione.InAttessa );
            Annulla.setVisible(true);
            TxtStatiConnessione.setText("in connessione con "+TxtIp.getText());
            TxtIp.setText("");
        } catch (UnknownHostException ex) {
            Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButConnettiActionPerformed

    private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
        Condivisi.Instance().SettaStatoConnessione(StatoConnessione.DisConnesso);
        Annulla.setVisible(false);
        TxtStatiConnessione.setText("");
    }//GEN-LAST:event_AnnullaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaccia().setVisible(true);
            }
        });
        
        try {
            ThreadServer s= new ThreadServer();
            s.start();
        } catch (IOException ex) {
            Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ThreadClient c= new ThreadClient();
            c.start();
        } catch (IOException ex) {
            Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
        }
        ThreadLogica l=new ThreadLogica();
        l.start();
        
    }
    
    public void AddMessaggio(String s)
    {
         SwingUtilities.invokeLater(new Runnable() {
            public void run() {
               TxtMessaggi.setText(TxtMessaggi.getText()+"\r\n"+s);
            }
        });
    }
    public void AnnullaVisibile(boolean b)
    {
         SwingUtilities.invokeLater(new Runnable() {
            public void run() {
               Annulla.setVisible(b);
               TxtStatiConnessione.setText("");
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton ButConnetti;
    private javax.swing.JButton Disconnetti;
    private javax.swing.JTextField TxtIp;
    private javax.swing.JTextArea TxtMessaggi;
    private javax.swing.JLabel TxtStatiConnessione;
    private javax.swing.JTextArea Txtmessaggio;
    private javax.swing.JButton butInviaMess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
